### ISSUE TITLE
Error when run the app

### ISSUE THREAD

**Issue by hendisantika** [andrlange/vaadin-grid-form-entities#1]
I follow the code --> Error when run the app
```
2024-11-20T09:19:54.884+07:00 ERROR 76678 --- [spring-boot-vaadin-grid-form-entities] [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Exception sending context initialized event to listener instance of class [com.vaadin.flow.spring.VaadinServletContextInitializer$CompositeServletContextListener]

java.lang.RuntimeException: Unable to initialize com.vaadin.flow.spring.VaadinServletContextInitializer$VaadinAppShellContextListener
	at com.vaadin.flow.spring.VaadinServletContextInitializer$FailFastServletContextListener.contextInitialized(VaadinServletContextInitializer.java:206) ~[vaadin-spring-24.5.5.jar:na]
	at com.vaadin.flow.spring.VaadinServletContextInitializer$CompositeServletContextListener.lambda$contextInitialized$0(VaadinServletContextInitializer.java:230) ~[vaadin-spring-24.5.5.jar:na]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597) ~[na:na]
	at com.vaadin.flow.spring.VaadinServletContextInitializer$CompositeServletContextListener.contextInitialized(VaadinServletContextInitializer.java:230) ~[vaadin-spring-24.5.5.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:3993) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4422) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1203) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1193) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:148) ~[na:na]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:749) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:772) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1203) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1193) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:148) ~[na:na]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:749) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:203) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:415) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:870) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:437) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:128) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:107) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:516) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:222) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:188) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:162) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:619) ~[spring-context-6.1.14.jar:6.1.14]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[spring-boot-3.3.5.jar:3.3.5]
	at id.my.hendisantika.vaadingridformentities.SpringBootVaadinGridFormEntitiesApplication.main(SpringBootVaadinGridFormEntitiesApplication.java:13) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50) ~[spring-boot-devtools-3.3.5.jar:3.3.5]
Caused by: com.vaadin.flow.server.InvalidApplicationConfigurationException: 

Found app shell configuration annotations in non `AppShellConfigurator` classes.
Please create a custom class implementing `AppShellConfigurator` and move the following annotations to it:
    - @Theme from id.my.hendisantika.vaadingridformentities.SpringBootVaadinGridFormEntitiesApplication

	at com.vaadin.flow.server.startup.VaadinAppShellInitializer.init(VaadinAppShellInitializer.java:139) ~[flow-server-24.5.5.jar:24.5.5]
	at com.vaadin.flow.spring.VaadinServletContextInitializer$VaadinAppShellContextListener.failFastContextInitialized(VaadinServletContextInitializer.java:688) ~[vaadin-spring-24.5.5.jar:na]
	at com.vaadin.flow.spring.VaadinServletContextInitializer$FailFastServletContextListener.contextInitialized(VaadinServletContextInitializer.java:202) ~[vaadin-spring-24.5.5.jar:na]
	... 44 common frames omitted

2024-11-20T09:19:54.886+07:00 ERROR 76678 --- [spring-boot-vaadin-grid-form-entities] [  restartedMain] o.apache.catalina.core.StandardContext   : One or more listeners failed to start. Full details will be found in the appropriate container log file
2024-11-20T09:19:54.886+07:00 ERROR 76678 --- [spring-boot-vaadin-grid-form-entities] [  restartedMain] o.apache.catalina.core.StandardContext   : Context [] startup failed due to previous errors
2024-11-20T09:19:54.895+07:00  INFO 76678 --- [spring-boot-vaadin-grid-form-entities] [  restartedMain] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-11-20T09:19:54.897+07:00  WARN 76678 --- [spring-boot-vaadin-grid-form-entities] [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server
2024-11-20T09:19:54.901+07:00  INFO 76678 --- [spring-boot-vaadin-grid-form-entities] [  restartedMain] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-11-20T09:19:54.908+07:00 ERROR 76678 --- [spring-boot-vaadin-grid-form-entities] [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:165) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:619) ~[spring-context-6.1.14.jar:6.1.14]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[spring-boot-3.3.5.jar:3.3.5]
	at id.my.hendisantika.vaadingridformentities.SpringBootVaadinGridFormEntitiesApplication.main(SpringBootVaadinGridFormEntitiesApplication.java:13) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50) ~[spring-boot-devtools-3.3.5.jar:3.3.5]
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:147) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:107) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:516) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:222) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:188) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:162) ~[spring-boot-3.3.5.jar:3.3.5]
	... 11 common frames omitted
Caused by: java.lang.IllegalStateException: StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[] failed to start
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.rethrowDeferredStartupExceptions(TomcatWebServer.java:209) ~[spring-boot-3.3.5.jar:3.3.5]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:131) ~[spring-boot-3.3.5.jar:3.3.5]
	... 16 common frames omitted


Process finished with exit code 0

```
Here's my repo https://github.com/hendisantika/spring-boot-vaadin-grid-form-entities

any suggestions?

Thanks

**Comment by hendisantika** [comment]
Why after add remove this annotation `@Theme(value = "vaadin-entity", variant = Lumo.DARK)`

It is working well?

Do We need to set something before adding that annotation/theme annotation?

**Comment by andrlange** [comment]
The theming works fine @Theme(value = "vaadin-entity", variant = Lumo.DARK). I removed the generated content and restarted without any errors. So I am removing the auto generated folder from frontend in this repo. Thanks

**Comment by hendisantika** [comment]
Can you run my cloning repo?

I still got this error @andrlange ?

Thanks

**Comment by andrlange** [comment]
Can you provide more infos? OS, Java version? How you run the application?

**Comment by hendisantika** [comment]
Sure, @andrlange .

I am using MacOS Seqouia 15.1
JDK 23
Maven 3.9.9
IntellIJ IDEA 2024.3.

I run this via IntelliJ IDEA. But, if i run using this command: `mvn clean spring-boot:run` still error

**Comment by andrlange** [comment]
@hendisantika  I am using the same setup, also testet it using Linux. I can not reproduce your error. 
also used: mvn spring-boot:run without any errors.
But I now puttet the Theme into it's own AppShellConfigurator bean. Can you please retry it with this change?

**Comment by hendisantika** [comment]
Can you clone my repo?

Here's my repo https://github.com/hendisantika/spring-boot-vaadin-grid-form-entities

Run in your local?

See if you can run it or not?

Thanks

**Comment by andrlange** [comment]
@hendisantika So I loaded your repo:
1) you need to let your main class: implements AppShellConfigurator -> needed for theme setup
2) you need to create the src/main/frontend folder having files and subfolders: 
  - index.js
  - themes
     -  vaadin-entity
 
@Theme(value = "vaadin-entity", variant = Lumo.DARK) is pointing to the folder under: frontend/themes/vaadin-entity!

**Comment by hendisantika** [comment]
OIC. I thought it was generated by vaadin automatically. Let me try it

**Comment by andrlange** [comment]
Also you can clone the newest repo version so you will have add and delete as well implemented

**Comment by hendisantika** [comment]
yayy... sounds good...

Thanks @andrlange

**Comment by hendisantika** [comment]
I already added the codes. But the add button doesn't show. What is missing ya @andrlange ?

<img width="445" alt="image" src="https://github.com/user-attachments/assets/b7ae660d-6737-4085-a1e1-43b29b2c826e">

<img width="392" alt="image" src="https://github.com/user-attachments/assets/4d09f6db-cc8c-4b9c-8a95-12820557e35c">

**Comment by andrlange** [comment]
@hendisantika Hi, you are mixing up old and new version of the code. If you replace the whole code of GenericView.java with the actual one you should see the add button (which is wrapped in the gridContainer and you don't use it) as well you should see the delete button in the Details View..

**Comment by hendisantika** [comment]
OIC. OK2. Thanks
